version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    container_name: backend_container
    build: ./API/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
