version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://user:pass@postgres/mydb
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - postgres
    ports:
      - "3002:3001"
